name: NRP
version: 0
author: moderator_man
main: com.oldschoolminecraft.nrp.Plugin
commands:
  recruit:
    description: Display your recruitment code
    default: op
    permission: nrp.use
  recruitment:
    description: Redeem a recruitment code
    default: op
    permission: nrp.use